twitter:
    consumer_key: Ogeq8gQMJJ4Pfkzx99jZPg
    consumer_secret: rx8h0Y11rFVV7Z3jE6MP3m2ewH7Cs02StNRIFvuOxs
    access_token_key: 2230148300-wNulSxhRJ0iuWAiqs9Jw6548QOZg8yaT2sRSF6O
    access_token_secret: wCukZDdmU64rZeZCfjbVcGXf31ydANfKb1pKVYbmUtDs7
streaming:
    interval: 100000
celebs:
    - MrsSOsbourne
    - DeborahMeaden
    - SophieEB
    - simonpegg
    - VanessaOnAir
    - stephenfry
    - Mark_Benton
    - duncanbannatyne
    - therealgokwan
    - jamieoliver
    - RealDMitchell
    - 2FionaFullerton
    - ashoztd
    - rickygervais
    - susannareid100
    - DerrenBrown
    - hairybikers
    - rustyrockets
    - jimmycarr
    - OfficialClancy
    - fearnecotton
